name: Java CI with JUnit

on:
  push: 
   branches: 
   - main
  workflow_dispatch:

jobs:
  build: 
   runs-on: ubuntu-latest 
   env:
    TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
    ENV TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Set up JDK 17"
      uses: actions/setup-java@v2
      with:
       java-version: '17'
       distribution: 'temurin'     
    - name: Build with Gradle
      run: ./gradlew build -xtest

    - name: Trivy with Gradle
      run: ./gradlew generateLockfile

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: './build/gradle.lockfile'
        trivy-config: trivy.yaml  

    # - name: Run tests
    #   run: ./gradlew test              