name: Java CI with JUnit

on:
  push: 
   branches: 
   - main
  workflow_dispatch:

jobs:
  build: 
   runs-on: ubuntu-latest 
   env:
    TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
    ENV TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Set up JDK 17"
      uses: actions/setup-java@v2
      with:
       java-version: '17'
       distribution: 'temurin'            
    - name: Build with Gradle
      run: ./gradlew build -xtest

    - name: Trivy with Gradle
      run: 
       - ./gradlew generateLockfile
       - cat 
       

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: './build/gradle.lockfile'
        output: ./build/result.json
        format: json

    - uses: actions/upload-artifact@v4
      with:
        name: lockfile
        path: ./build/gradle.lockfile
        compression-level: 0 # no compression


    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: trivy-result
        path: ./build/result.json

    # - name: Run tests
    #   run: ./gradlew test              