name: Java CI with JUnit

on:
  push: 
   branches: 
   - main
  workflow_dispatch:

jobs:
  build: 
   runs-on: ubuntu-latest 
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Set up JDK 17"
      uses: actions/setup-java@v2
      with:
       java-version: '17'
       distribution: 'temurin'     
    - name: Build with Gradle
      run: ./gradlew build 

    - name: Trivy with Gradle
      run: ./gradlew generateLockfile

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.20.0
    - name: Run tests
      run: ./gradlew test      
      with:
        scan-type: 'fs'
        scan-ref: './build/gradle.lockfile'
        trivy-config: trivy.yaml  